apiVersion: v1
kind: Service
metadata:
  labels:
    app: us-deliverymanager
  name: us-deliverymanager
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8031
  selector:
    app: us-deliverymanager
status:
  loadBalancer: {}
