spring:
  datasource:
    url: jdbc:mysql://ci02fulfillment.c4rjguxjh6uc.us-east-1.rds.amazonaws.com:3306/ci02fulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: carloscalla
    password: elpreciomasbajo
    #url: jdbc:mysql://uatfulfillment.c4rjguxjh6uc.us-east-1.rds.amazonaws.com:3306/uatfulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    #username: operaciones
    #password: Operaciones2020
    #url: jdbc:mysql://qa02fulfillment.c4rjguxjh6uc.us-east-1.rds.amazonaws.com:3306/qa02fulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    #username: operaciones
    #password: Operaciones2020.
  mvc:
    async:
      request-timeout: 240000
external-service:
  audit:
    create-order: http://auditci02.backend.cindibyinkafarma.com/audit/order
    create-order-history-audit: http://auditci02.backend.cindibyinkafarma.com/audit/order/history
    update-order-history-audit: http://auditci02.backend.cindibyinkafarma.com/audit/order/history
    connect-timeout: 10000
    read-timeout: 10000
  dispatcher:
    insink-tracker:
      uri: http://dduat.backend.cindibyinkafarma.com/order/insink-tracker
      uri-mifarma: http://ddmfci02.backend.cindibyinkafarma.com/order/insink-tracker
      connect-timeout: 30000
      read-timeout: 60000
    tracker:
      uri: http://dduat.backend.cindibyinkafarma.com/order/tracker
      uri-mifarma: http://ddmfci02.backend.cindibyinkafarma.com/order/tracker
      connect-timeout: 30000
      read-timeout: 60000
    legacy-system:
      uri: http://dduat.backend.cindibyinkafarma.com/order/legacy-system
      uri-mifarma: http://ddmfci02.backend.cindibyinkafarma.com/order/legacy-system
      connect-timeout: 30000
      read-timeout: 60000
    order-ecommerce:
      uri: http://dduat.backend.cindibyinkafarma.com/order/ecommerce
      uri-mifarma: http://ddmfci02.backend.cindibyinkafarma.com/order/ecommerce
      connect-timeout: 30000
      read-timeout: 60000
  inkatracker-lite:
    create-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/orders/create
      connect-timeout: 30000
      read-timeout: 60000
    update-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/v2/unattended-orders
      connect-timeout: 30000
      read-timeout: 60000
    update-onlinepayment-status-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/onlinepayment/orders
      connect-timeout: 30000
      read-timeout: 60000
  inkatracker:
    create-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/orders/create
      connect-timeout: 30000
      read-timeout: 60000
    update-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/orders/create
      connect-timeout: 30000
      read-timeout: 60000
    update-status-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/orders
      connect-timeout: 30000
      read-timeout: 60000
    update-onlinepayment-status-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/nvr/onlinepayment/orders
      connect-timeout: 30000
      read-timeout: 60000
  order-tracker:
    create-order:
      uri: http://inkatrackerliteci02.backend.cindibyinkafarma.com/order
      connect-timeout: 10000
      read-timeout: 120000
    assign-orders:
      uri: http://ordertrackerci02.backend.cindibyinkafarma.com/orders/status/assigned
      connect-timeout: 10000
      read-timeout: 120000
    unassign-orders:
      uri: http://ordertrackerci02.backend.cindibyinkafarma.com/orders/status/unassigned
      connect-timeout: 10000
      read-timeout: 120000
    update-order-status:
      uri: http://ordertrackerci02.backend.cindibyinkafarma.com/order
      connect-timeout: 10000
      read-timeout: 120000
    update-partial:
      uri: http://ordertrackerci02.backend.cindibyinkafarma.com/nvr/order/partial
      connect-timeout: 10000
      read-timeout: 120000
  fulfillment-center:
    get-center:
      uri: http://fulfillment-centerci02.backend.cindibyinkafarma.com/fulfillment/store/
      connect-timeout: 15000
      read-timeout: 30000
  seller-center:
    host: http://sellercenterci01.backend.cindibyinkafarma.com
    services:
      update-status:
        uri: /order/statusOrder/{ecommerceId}/{statusCode}
        connect-timeout: 15000
        read-timeout: 30000
      add-controversy:
        uri: /sellercenter/orders/
        connect-timeout: 10000
        read-timeout: 120000
  online-payment:
    liquidated:
      uri: https://visauat.cindibyinkafarma.com/visa/confirmation
      uri-mifa: https://visamfci02.cindibyinkafarma.com/visa/confirmation
      connect-timeout: 10000
      read-timeout: 120000
    rejected:
      uri: https://visauat.cindibyinkafarma.com/visa/rejected
      uri-mifa: https://visamfci02.cindibyinkafarma.com/visa/rejected
      connect-timeout: 10000
      read-timeout: 120000
  notification-lambda:
    send-message:
      uri: https://h66xgj99rd.execute-api.us-east-1.amazonaws.com/QA02/messaging
      connect-timeout: 10000
      read-timeout: 120000
  liquidation:
    create-order:
      uri: http://liquidationci02.backend.cindibyinkafarma.com/omni/liquidation/v1.0.0/orders
      connect-timeout: 10000
      read-timeout: 120000
    update-order:
      uri: http://liquidationci02.backend.cindibyinkafarma.com/omni/liquidation/v1.0.0/orders
      connect-timeout: 10000
      read-timeout: 120000
    update-order-online:
      uri: http://liquidationci02.backend.cindibyinkafarma.com/omni/liquidation/v1.0.0/orders/dc
      connect-timeout: 10000
      read-timeout: 120000
  insink:
    get-order-callcenter:
      uri: http://insink-aws-prueba.backend.inkafarma.pe/get/order
      connect-timeout: 30000
      read-timeout: 60000
  legacy-bridge:
    release-stock:
      uri: http://localhost:8036/omni/v1.0.0/legacy/release-stock/
      connect-timeout: 30000
      read-timeout: 60000
  manage-partner:
    update-status: http://fps-wsmanagepartneruat.backend.cindibyinkafarma.com/api/v1/managePartner/event/notify/
