spring:
  datasource:
    url: jdbc:mysql://fulfillment.prd.internal:3306/prdfulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: operaciones
    password: Operaciones2020
external-service:
  audit:
    create-order: http://us-audit/audit/order
    time-out: 20000
  dispatcher:
    insink-tracker:
      uri: http://us-dd/order/insink-tracker
      uri-mifarma: http://ddmfprd.backend.mifarma.com.pe/order/insink-tracker
      connect-timeout: 240000
      read-timeout: 480
    tracker:
      uri: http://us-dd/order/tracker
      uri-mifarma: http://ddmfprd.backend.mifarma.com.pe/order/tracker
      connect-timeout: 240000
      read-timeout: 480
  inkatracker-lite:
    update-order:
      uri: http://us-inkatrackerlite/v2/unattended-orders
      connect-timeout: 240000
      read-timeout: 360
  order-tracker:
    create-order:
      uri: http://us-ordertracker/ordertracker
      connect-timeout: 20000
      read-timeout: 240000