spring:
  datasource:
    url: jdbc:mysql://fulfillment.prd.internal:3306/prdfulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: operaciones
    password: Operaciones2020
  mvc:
    async:
      request-timeout: 240000
external-service:
  audit:
    create-order: http://us-audit/audit/order
    time-out: 20000
  dispatcher:
    insink-tracker:
      uri: http://us-dd/order/insink-tracker
      uri-mifarma: http://ddmfprd.backend.mifarma.com.pe/order/insink-tracker
      connect-timeout: 30000
      read-timeout: 480
    tracker:
      uri: http://us-dd/order/tracker
      uri-mifarma: http://ddmfprd.backend.mifarma.com.pe/order/tracker
      connect-timeout: 30000
      read-timeout: 480
    legacy-system:
      uri: http://us-dd/order/legacy-system
      uri-mifarma: http://ddmfci02.backend.cindyinkafarma.com/order/legacy-system
      connect-timeout: 240000
      read-timeout: 480
  inkatracker-lite:
    create-order:
      uri: http://us-inkatrackerlite/nvr/orders/create
      connect-timeout: 240
      read-timeout: 360
    update-order:
      uri: http://us-inkatrackerlite/v2/unattended-orders
      connect-timeout: 30000
      read-timeout: 360
  inkatracker:
    create-order:
      uri: http://us-inkatracker/nvr/orders/create
      connect-timeout: 240000
      read-timeout: 480
    update-order:
      uri: http://us-inkatracker/nvr/orders/create
      connect-timeout: 240000
      read-timeout: 480
    update-status-order:
      uri: http://us-inkatracker/nvr/orders
      connect-timeout: 240000
      read-timeout: 480
  temporary:
    create-order:
      uri: http://us-temporary/nvr/orders/create
      connect-timeout: 240000
      read-timeout: 480
    update-order:
      uri: http://us-temporary/nvr/orders/update
      connect-timeout: 240000
      read-timeout: 480
  order-tracker:
    create-order:
      uri: http://us-ordertracker/order
      connect-timeout: 10000
      read-timeout: 120000
    assign-orders:
      uri: http://us-ordertracker/orders/status/assigned
      connect-timeout: 10000
      read-timeout: 120000
    unassign-orders:
      uri: http://us-ordertracker/orders/status/unassigned
      connect-timeout: 10000
      read-timeout: 120000
    update-order-status:
      uri: http://us-ordertracker/order
      connect-timeout: 10000
      read-timeout: 120000
  fulfillment-center:
    get-center:
      uri: http://us-fulfillment-center/fulfillment/store/
      connect-timeout: 10000
      read-timeout: 120000
    get-company-center:
      uri: http://us-fulfillment-center/fulfillment/store/
      connect-timeout: 10000
      read-timeout: 120000