spring:
  datasource:
    url: jdbc:mysql://qa02fulfillment.c4rjguxjh6uc.us-east-1.rds.amazonaws.com:3306/qa02fulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: operaciones
    password: Operaciones2020.
external-service:
  audit:
    create-order: http://us-audit/audit/order
    time-out: 20000
  dispatcher:
    insink-tracker:
      uri: http://us-dd/order/insink-tracker
      uri-mifarma: http://ddmfqa.backend.cindyinkafarma.com/order/insink-tracker
      connect-timeout: 240000
      read-timeout: 480
    tracker:
      uri: http://us-dd/order/tracker
      uri-mifarma: http://ddmfqa.backend.cindyinkafarma.com/order/tracker
      connect-timeout: 240000
      read-timeout: 480
  inkatracker-lite:
    update-order:
      uri: http://us-inkatrackerlite/v2/unattended-orders
      connect-timeout: 240
      read-timeout: 360
  inkatracker:
    create-order:
      uri: http://us-inkatracker/nvr/orders/create
      connect-timeout: 240000
      read-timeout: 480
    update-order:
      uri: http://us-inkatracker/nvr/orders/create
      connect-timeout: 240000
      read-timeout: 480
    update-status-order:
      uri: http://us-inkatracker/nvr/orders/update
      connect-timeout: 240000
      read-timeout: 480
  order-tracker:
    create-order:
      uri: http://us-ordertracker/ordertracker
      connect-timeout: 10000
      read-timeout: 120000