spring:
  datasource:
    url: jdbc:mysql://ci02fulfillment.c4rjguxjh6uc.us-east-1.rds.amazonaws.com:3306/ci02fulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: carloscalla
    password: elpreciomasbajo
external-service:
  audit:
    create-order: http://localhost:8032/audit/order
    time-out: 20000
  dispatcher:
    insink-tracker:
      uri: http://us-dd/order/insink-tracker/{orderId}
      connect-timeout: 10000
      read-timeout: 120000
    tracker:
      uri: http://us-dd/order/tracker/{orderId}
      connect-timeout: 10000
      read-timeout: 120000
  inkatracker-lite:
    update-order:
      uri: http://localhost:8283/v2/unattended-orders
      connect-timeout: 10000
      read-timeout: 120000
  order-tracker:
    create-order:
      uri: http://localhost:8030/ordertracker
      connect-timeout: 10000
      read-timeout: 120000