spring:
  datasource:
    url: jdbc:mysql://fulfillment.qa02.internal:3306/qa02fulfillment?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: operaciones
    password: Operaciones2020.
external-service:
  audit:
    create-order: http://us-audit/audit/order
    time-out: 20000
  dispatcher:
    insink-tracker:
      uri: http://us-dd/order/insink-tracker/{orderId}
      connect-timeout: 360
      read-timeout: 480
    tracker:
      uri: http://us-dd/order/tracker/{orderId}
      connect-timeout: 360
      read-timeout: 480
  inkatracker-lite:
    update-order:
      uri: http://us-inkatrackerlite/v2/unattended-orders
      connect-timeout: 240
      read-timeout: 360
  order-tracker:
    create-order:
      uri: http://us-ordertracker/ordertracker
      connect-timeout: 10000
      read-timeout: 120000