apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deliverymanager
  labels:
    app: us-deliverymanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-deliverymanager
  template:
    metadata:
      labels:
        app: us-deliverymanager
    spec:
      containers:
      - name: us-deliverymanager
        image: 519901771307.dkr.ecr.us-west-2.amazonaws.com/deliverymanager-service:{{TAG}}
        env:
        - name: environment
          value: "prd"
        - name: LOG_LEVEL_SYSTEM
          value: "INFO"
        - name: LOG_LEVEL_BUSINESS
          value: "ERROR"
        - name: newrelic
          value: "-javaagent:/usr/src/service/newrelic.jar"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: licensekey
        ports:
        - containerPort: 8031
        resources:
          limits:
            cpu: 800m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 1024Mi
      restartPolicy: Always
