pipeline {
    agent { label 'slave1'}
    options {
        ansiColor('xterm')
    }
    stages {

        stage ('Apply Service') {
            steps {
                sh "kubectl apply -f devops/k8/prd/deliverymanager-service.yml"
            }

        }
        stage ('Apply Deployment') {
            steps {
                sh 'cat devops/k8/prd/deliverymanager-deployment.yml | sed "s/{{TAG}}/$TAG/g" | kubectl apply -f -'


            }

        }

    }
}
