apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-ordermanager
  labels:
    app: us-ordermanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: us-ordermanager
  template:
    metadata:
      labels:
        app: us-ordermanager
    spec:
      containers:
      - name: us-ordermanager
        image: 519901771307.dkr.ecr.us-west-2.amazonaws.com/ordermanager-service:{{TAG}}
        env:
        - name: environment
          value: "prd"
        - name: LOG_LEVEL_SYSTEM
          value: "INFO"
        - name: LOG_LEVEL_BUSINESS
          value: "ERROR"
        ports:
        - containerPort: 8031
        resources:
          limits:
            memory: 1.5Gi
          requests:
            memory: 1.5Gi
      restartPolicy: Always
