ALTER TABLE `service_type`
ADD COLUMN `send_new_code_enabled` tinyint(1) DEFAULT NULL 0 AFTER `description`;

UPDATE  service_type
SET     send_new_code_enabled = 1
WHERE  code in
('INKATRACKER_CALL', 'INKATRACKER_RAD', 'INKATRACKER_AM_PM','INKATRACKER_EXP','INKATRACKER_PROG','INKATRACKER_CALL_AM_PM',
'INKATRACKER_CALL_EXP','INKATRACKER_CALL_PROG','INKATRACKER_CALL_RET','TEMPORARY_AM_PM','TEMPORARY_EXP','TEMPORARY_PROG',
'TEMPORARY_RAD','TEMPORARY_RET');


