INSERT INTO cancellation_code_reason VALUES
('R01','OMNI_DELIVERY','REJECTED','Cliente no está en la dirección de entrega','Cliente no está en la dirección de entrega',1),
('R02','OMNI_DELIVERY','REJECTED','Error del cliente al solicitar productos','Error del cliente al solicitar productos',1),
('R03','OMNI_DELIVERY','REJECTED','Cliente no desea el pedido','Cliente no desea el pedido',1),
('R04','OMNI_DELIVERY','REJECTED','La dirección no coincide con el punto de entrega','La dirección no coincide con el punto de entrega',1),
('R05','OMNI_DELIVERY','REJECTED','Pedido no llego en el horario ofrecido','Pedido no llego en el horario ofrecido',1),
('R06','OMNI_DELIVERY','REJECTED','No es posible ubicar la dirección de entrega','No es posible ubicar la dirección de entrega',1),
('R07','OMNI_DELIVERY','REJECTED','Pedido duplicado','Pedido duplicado',1),
('R08','OMNI_DELIVERY','REJECTED','Cliente no vive en la dirección de entrega','Cliente no vive en la dirección de entrega',1),
('R09','OMNI_DELIVERY','REJECTED','Zona sin cobertura','Zona sin cobertura',1),
('R10','OMNI_DELIVERY','REJECTED','Zona peligrosa','Zona peligrosa',1),
('R11','OMNI_DELIVERY','REJECTED','Cambio de forma de pago','Cambio de forma de pago',1),
('R12','OMNI_DELIVERY','REJECTED','Cliente no tiene receta médica','Cliente no tiene receta médica',1),
('R13','OMNI_DELIVERY','REJECTED','Error de inkafarma al elegir los productos','Error de inkafarma al elegir los productos',1),
('R14','OMNI_DELIVERY','REJECTED','Productos dañados','Productos dañados',1),
('R15','OMNI_DELIVERY','REJECTED','Cambio de comprobante de pago','Cambio de comprobante de pago',1),
('R16','OMNI_DELIVERY','REJECTED','Cliente rechazo por cambio de presentacion','Cliente rechazo por cambio de presentacion',1);