INSERT INTO cancellation_code_reason VALUES
('C100','INKATRACKER-WEB','CANCELLED','Cliente se equivoca al solicitar productos','Error en la generación del pedido',1),
('C100','FARMADASHBOARD','CANCELLED','Cliente se equivoca al solicitar productos','Error en la generación del pedido',1),
('C101','FARMADASHBOARD','CANCELLED','Pedido duplicado','Pedido previamente entregado',1),
('C101','INKATRACKER-WEB','CANCELLED','Pedido duplicado','Pedido previamente entregado',1),
('C102','INKAMOTO','CANCELLED','Cliente no se encuentra en el punto de entrega','Problemas al verificar la información de tu nombre o dirección de entrega',1),
('C103','INKAMOTO','CANCELLED','Cliente no presenta receta','Cliente no presenta receta',1),
('C104','INKATRACKER-WEB','CANCELLED','Regeneración de pedido','No es posible reprogramar el pedido',1),
('C104','FARMADASHBOARD','CANCELLED','Regeneración de pedido','No es posible reprogramar el pedido',1),
('C105','INKATRACKER-WEB','CANCELLED','Stock no disponible - Desfase','No hay stock de uno de los productos solicitados',1),
('C105','FARMADASHBOARD','CANCELLED','Stock no disponible - Desfase','No hay stock de uno de los productos solicitados',1),
('C106','INKATRACKER-WEB','CANCELLED','Stock no disponible - ERI','No hay stock de uno de los productos solicitados',1),
('C106','FARMADASHBOARD','CANCELLED','Stock no disponible - ERI','No hay stock de uno de los productos solicitados',1),
('C107','INKATRACKER-WEB','CANCELLED','La dirección no coincide con el punto de entrega','Problemas al verificar la información de tu nombre o dirección de entrega',1),
('C107','FARMADASHBOARD','CANCELLED','La dirección no coincide con el punto de entrega','Problemas al verificar la información de tu nombre o dirección de entrega',1),
('C108','FARMADASHBOARD','CANCELLED','Punto de entrega fuera de la cobertura delivery','Dificultades en las vías de acceso en camino a tu dirección',1),
('C109','INKATRACKER-WEB','CANCELLED','Los productos no fueron los solicitados por el cliente','Problemas con los productos enviados',1),
('C109','FARMADASHBOARD','CANCELLED','Los productos no fueron los solicitados por el cliente','Problemas con los productos enviados',1),
('C110','INKAMOTO','CANCELLED','Producto llegó en mal estado','Problemas con los productos enviados',1),
('C111','INKATRACKER-WEB','CANCELLED','Cliente no tiene el método de pago solicitado','Por cambio en la forma de pago',1),
('C111','FARMADASHBOARD','CANCELLED','Cliente no tiene el método de pago solicitado','Por cambio en la forma de pago',1),
('C112','INKATRACKER-WEB','CANCELLED','Posible fraude','Pedido fue observado',1),
('C112','FARMADASHBOARD','CANCELLED','Posible fraude','Pedido fue observado',1),
('C113','INKATRACKER-WEB','CANCELLED','Cliente mayorista','Uno de tus productos superó el limite de compra permitido',1),
('C113','FARMADASHBOARD','CANCELLED','Cliente mayorista','Uno de tus productos superó el limite de compra permitido',1),
('C114','INKATRACKER-WEB','CANCELLED','Técnico no toma correctamente la solicitud del cliente','Dificultades técnicas al atender tu pedido',1),
('C114','FARMADASHBOARD','CANCELLED','Técnico no toma correctamente la solicitud del cliente','Dificultades técnicas al atender tu pedido',1),
('C117','INKATRACKER-WEB','CANCELLED','Reprogramación por sistemas','Dificultades técnicas al atender tu pedido',1),
('C117','FARMADASHBOARD','CANCELLED','Reprogramación por sistemas','Dificultades técnicas al atender tu pedido',1),
('C118','INKATRACKER-WEB','CANCELLED','Pedido de prueba para sistemas','Prueba de sistemas',1),
('C119','FARMADASHBOARD','CANCELLED','Pedido de prueba para sistemas','Prueba de sistemas',1);

