ALTER TABLE `address_fulfillment`
CHANGE COLUMN `number` `number` VARCHAR(256) NULL;

ALTER TABLE `payment_method`
CHANGE COLUMN `bin` `bin` VARCHAR(256) NULL;

ALTER TABLE `service_type`
ADD COLUMN `send_new_flow_enabled` tinyint(1) DEFAULT 0 AFTER `send_new_code_enabled`;

UPDATE  service_type
SET     send_new_flow_enabled = 1
WHERE  code in
('INKATRACKER_LITE_AM_PM', 'INKATRACKER_LITE_CALL_AM_PM', 'INKATRACKER_LITE_CALL_EXP','INKATRACKER_LITE_CALL_PROG',
'INKATRACKER_LITE_CALL_RAD','INKATRACKER_LITE_CALL_RET','INKATRACKER_LITE_EXP','INKATRACKER_LITE_PROG',
'INKATRACKER_LITE_RAD','INKATRACKER_LITE_RET');

